### ISSUE TITLE
Segfault using gir with WebView

### ISSUE THREAD

**Issue by jjl** [Kalimehtar/gir#2]
Hi,

Trying to use gir to integrate with webkit via libwebkitgtk+ causes a segfault The equivalent works absolutely fine using the python gir libraries.

Using gtk 3.4, racket 6.1.1, debian.

```
≺≻ (define wk (gi-ffi "WebKit"))
≺≻ (wk 'WebView 'new)

(racket:15070): Gtk-CRITICAL **: gtk_text_attributes_ref: assertion `values != NULL' failed

(racket:15070): Gtk-CRITICAL **: gtk_text_attributes_ref: assertion `values != NULL' failed

(racket:15070): Pango-CRITICAL **: pango_layout_new: assertion `context != NULL' failed
SIGSEGV MAPERR si_code 1 fault on addr 0x38
```

**Comment by Kalimehtar** [comment]
It seems,  that necessary dynamic library is not loaded. Try add correct (ffi-lib ..) before calling gi-ffi.
