### ISSUE TITLE
Fail when running inside DrRacket

### ISSUE THREAD

**Issue by nodrygo** [Kalimehtar/gir#3]
when running inside DrRacket, DrRacket is frozen and the Gtk in is not displayed
may be it should start in a PLACE when inside DrRacket ? 
work fine from racket cmd line

**Comment by Kalimehtar** [comment]
You may explicitly run you code inside a place. In most cases additional thread is unnecessary for the library user.

**Comment by Kalimehtar** [comment]
> and the Gtk in is not displayed

Should be displayed. If I run gir/test in DrRacket, it works OK. If you have code, that hangs DrRacket, please post it.
